### ISSUE TITLE
Selenium::WebDriver::Error::NoSuchDriverError

### ISSUE THREAD

**Issue by jwarykowski** [vertis/selenium-webdriver#5]
Hi,

I'm having a strange problem running our suite of capybara/selenium tests. They will be running as expected for 30 mins and then suddenly we get the following error:

 no such session
        (Driver info: chromedriver=2.8.240825,platform=Linux 3.2.0-4-amd64 x86_64) (Selenium::WebDriver::Error::NoSuchDriverError)
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/response.rb:51:in `assert_ok'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/response.rb:15:in`initialize'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/http/common.rb:59:in`create_response'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/http/common.rb:40:in`call'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/bridge.rb:634:in `raw_execute'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/bridge.rb:612:in`execute'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/bridge.rb:166:in `getCurrentUrl'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/common/driver.rb:120:in`current_url'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.1/lib/capybara/selenium/driver.rb:65:in `current_url'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.1/lib/capybara/session.rb:143:in`current_url'
      /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      /var/lib/jenkins/workspace/QA - UI Integration/features/support/hooks.rb:12:in`After'

For some reason it is losing its appears to losing its session/connection with the chrome browser and bailing out.

Has anyone seen this issue before? Any feedback would be greatly appreciated.

Regards,
Jon

**Comment by vertis** [comment]
Hi Jon,
   This is not really intended for public consumption (it's a personal mirror of the selenium-webdriver project, because it isn't/wasn't on github). As such it's quite old.

Regards,

Luke

**Comment by jwarykowski** [comment]
Hi Luke,

No worries, I noticed this as soon as I raised this and added a new issue to the Google Code project.

Cheers,
Jon

**Comment by vertis** [comment]
No probs, just didn't want you to be confused :)
